// Generated by CoffeeScript 1.6.3
(function() {
  var ObjectID, TrelloView, Trellos, fs, handlebars, should, sugar, _;

  fs = require('fs');

  _ = require('underscore');

  ObjectID = require('mongodb').ObjectID;

  should = require('should');

  handlebars = require('handlebars');

  Trellos = require('../models/trellos');

  sugar = require('sugar');

  module.exports = TrelloView = (function() {
    TrelloView.templates = {
      duecard: {
        path: 'templates/duecard.tmpl',
        template: null
      },
      list_table: {
        path: 'templates/list-tabular.tmpl',
        template: null
      },
      list_table_nocard: {
        path: 'templates/list-tabular-nocard.tmpl',
        template: null
      },
      list_row: {
        path: 'templates/list-row.tmpl',
        template: null
      },
      action: {
        path: 'templates/actions.tmpl',
        template: null
      }
    };

    TrelloView.template_compiled = false;

    function TrelloView() {
      var keys,
        _this = this;
      if (TrelloView.template_compiled !== true) {
        keys = _.keys(TrelloView.templates);
        _.each(keys, function(key) {
          var tmpl;
          tmpl = fs.readFileSync(__dirname + '/' + TrelloView.templates[key].path);
          return TrelloView.templates[key].template = handlebars.compile(tmpl.toString());
        });
        TrelloView.template_compiled = true;
      }
    }

    TrelloView.prototype.collect_cards_per_due = function(all_cards) {
      var cardids,
        _this = this;
      cardids = {
        past: [],
        today: [],
        soon: []
      };
      _.each(all_cards, function(cards) {
        return _.each(cards.cards, function(card) {
          var days_diff, due, now;
          if (card.due) {
            due = new Date(card.due);
            now = new Date();
            days_diff = (due - now) / 86400000;
            if (days_diff < 0) {
              return cardids.past.push(card.id);
            } else {
              if (days_diff < 1) {
                return cardids.today.push(card.id);
              } else if (days_diff < 7) {
                return cardids.soon.push(card.id);
              }
            }
          }
        });
      });
      return cardids;
    };

    TrelloView.prototype.all_org_names = function(alldata) {
      var orgs,
        _this = this;
      orgs = _.map(alldata.boards, function(board) {
        return board.org_name;
      });
      return _.uniq(orgs);
    };

    TrelloView.prototype.lookup_card_by_id = function(alldata, card_id) {
      var cards, cr,
        _this = this;
      cr = null;
      cards = _.find(alldata.cards, function(cards) {
        cr = _.find(cards.cards, function(card) {
          return card.id === card_id;
        });
        return !_.isUndefined(cr);
      });
      return [cards, cr];
    };

    TrelloView.prototype.lookup_cards_by_listid = function(alldata, list_id) {
      var cards, cr,
        _this = this;
      cr = null;
      cards = _.find(alldata.cards, function(cards) {
        return cards.list_id === list_id;
      });
      return cards;
    };

    TrelloView.prototype.lookup_board_by_id = function(alldata, board_id) {
      var bd;
      bd = _.find(alldata.boards, function(board) {
        return board.boards.id === board_id;
      });
      return bd;
    };

    TrelloView.prototype.lookup_list_by_id = function(alldata, board_id, list_id) {
      var lists, lst,
        _this = this;
      lst = null;
      lists = _.find(alldata.lists, function(list) {
        lst = null;
        if (list.board_id === board_id) {
          lst = _.find(list.lists, function(lst) {
            return lst.id === list_id;
          });
        }
        return lst !== null && !_.isUndefined(lst);
      });
      return [lists, lst];
    };

    TrelloView.prototype.card_member = function(alldata, card) {
      var member_names, members,
        _this = this;
      if (0 < card.idMembers.length) {
        member_names = [];
        _.each(card.idMembers, function(mem_id) {
          var m;
          m = _.find(alldata.members, function(mem) {
            return mem_id === mem.member_id;
          });
          return member_names.push(m.name);
        });
        return members = member_names.join(',');
      } else {
        return 'None';
      }
    };

    TrelloView.prototype.list_cards_dueform = function(alldata, cardids, fn) {
      var htmls,
        _this = this;
      htmls = [];
      _.each(cardids, function(card_id) {
        var aboard, acard, alist, context, duedate, members;
        acard = _this.lookup_card_by_id(alldata, card_id);
        aboard = _this.lookup_board_by_id(alldata, acard[0].board_id);
        alist = _this.lookup_list_by_id(alldata, acard[0].board_id, acard[0].list_id);
        members = _this.card_member(alldata, acard[1]);
        duedate = Date.create(acard[1].due).format("{Mon} {d}, {yyyy} at {h}:{mm} {tt} UCT{tz}");
        context = {
          board_name: aboard.boards.name,
          board_url: aboard.boards.url,
          org_name: aboard.org_name,
          list_name: alist[1].name,
          list_url: "",
          card_name: acard[1].name,
          card_url: acard[1].url,
          due: duedate,
          assigned_to: members
        };
        return htmls.push(TrelloView.templates.duecard.template(context));
      });
      if (cardids.length === 0) {
        htmls.push('<divNo Cards</div>');
      }
      return htmls.join('<br>\n');
    };

    TrelloView.prototype.list_tabular = function(alldata, lists) {
      var html, rows, tables,
        _this = this;
      tables = [];
      rows = [];
      _.each(lists.lists, function(list) {
        var cards, trs;
        cards = _this.lookup_cards_by_listid(alldata, list.id);
        if (!_.isUndefined(cards)) {
          _.each(cards.cards, function(card) {
            var context, duedate;
            if (card.due) {
              duedate = Date.create(card.due).format("{Mon} {d}, {h}:{mm} {TT}");
            } else {
              duedate = "None";
            }
            context = {
              card_name: card.name,
              assigned_to: _this.card_member(alldata, card),
              due_short: duedate,
              comments: card.badges.comments.toString()
            };
            return rows.push(TrelloView.templates.list_row.template(context));
          });
          trs = rows.join('\n');
          return tables.push(TrelloView.templates.list_table.template({
            list_name: list.name,
            rows: trs
          }));
        } else {
          return tables.push(TrelloView.templates.list_table_nocard.template({
            list_name: list.name
          }));
        }
      });
      return html = tables.join('\n');
    };

    TrelloView.prototype.render_action = function(action) {
      var context;
      context = {
        full_name: action.memberCreator.fullName,
        action: action.type,
        date: Date.create(action.date).format("{Mon} {d}, {h}:{mm} {TT}")
      };
      return TrelloView.templates.action.template(context);
    };

    TrelloView.prototype.recent_actions = function(alldata, board_id) {
      var actions, len, size, sorted,
        _this = this;
      actions = _.filter(alldata.actions, function(action) {
        return action.data.board.id === board_id;
      });
      sorted = _.sortBy(actions, function(action) {
        return (new Date(action.date)).getTime();
      });
      len = sorted.length;
      if (len < 5) {
        size = len;
      } else {
        size = 5;
      }
      return (sorted.slice(sorted.length - size, len)).reverse();
    };

    TrelloView.prototype.renderHtml = function(trellos, user_id, fn) {
      var _this = this;
      return trellos.get_all_data(user_id, function(err, all) {
        var htmls, orgs, ret, wtf;
        if (err) {
          return fn(500, all);
        } else {
          htmls = [];
          wtf = _this.collect_cards_per_due(all.cards);
          htmls.push('<h5><i>Due Today</i></h5>');
          htmls.push(_this.list_cards_dueform(all, wtf.today));
          htmls.push('<h5><i>Due Soon</i></h5>');
          htmls.push(_this.list_cards_dueform(all, wtf.soon));
          htmls.push('<h5><i>Past Due</i></h5>');
          htmls.push(_this.list_cards_dueform(all, wtf.past));
          ret = htmls.join("\n");
          orgs = _this.all_org_names(all);
          ret += "<br><h4>Recent Activities</h4>";
          _.each(orgs, function(org) {
            var boards_for_org;
            boards_for_org = _.filter(all.boards, function(bd) {
              return bd.org_name === org;
            });
            return _.each(boards_for_org, function(board) {
              var actions;
              ret += "<br><h4><i>Board: " + org + " / " + board.boards.name + "</i></h4>";
              actions = _this.recent_actions(all, board.boards.id);
              return _.each(actions, function(a) {
                return ret += _this.render_action(a);
              });
            });
          });
          ret += "<br><h4>Boards Snapshot</h4>";
          _.each(orgs, function(org) {
            var boards_for_org;
            boards_for_org = _.filter(all.boards, function(bd) {
              return bd.org_name === org;
            });
            return _.each(boards_for_org, function(board) {
              var lists;
              lists = _.filter(all.lists, function(list) {
                return list.board_id === board.boards.id;
              });
              ret += "<br><h4><i>Board: " + org + " / " + board.boards.name + "</i></h4>";
              return _.each(lists, function(lists) {
                return ret += _this.list_tabular(all, lists);
              });
            });
          });
          ret += "<br>";
          return fn(null, ret);
        }
      });
    };

    TrelloView.prototype.getSummary = function(user, fn) {
      var trellos;
      trellos = new Trellos();
      return this.renderHtml(trellos, new ObjectID(user._id.toString()), fn);
    };

    return TrelloView;

  })();

}).call(this);
