// Generated by CoffeeScript 1.6.3
(function() {
  var dbconnection, mongodb, should;

  mongodb = require('mongodb');

  should = require('should');

  module.exports = dbconnection = (function() {
    dbconnection.client = null;

    dbconnection.dbopts = {
      host: "127.0.0.1",
      port: 27017,
      db: "trellme"
    };

    dbconnection.p_client = null;

    function dbconnection() {
      if (dbconnection.client === null) {
        dbconnection.client = new mongodb.Db(dbconnection.dbopts.db, new mongodb.Server(dbconnection.dbopts.host, dbconnection.dbopts.port, {
          auto_reconnect: true
        }), {
          native_parser: true,
          w: 1
        });
      }
    }

    dbconnection.get_client = function(fn) {
      if (dbconnection.p_client !== null) {
        fn(null, dbconnection.p_client);
        return;
      }
      return dbconnection.client.open(function(err, p_client) {
        if (err) {
          return fn(500, 'client.open fail');
        } else {
          dbconnection.p_client = p_client;
          return fn(null, p_client);
        }
      });
    };

    return dbconnection;

  })();

}).call(this);
