// Generated by CoffeeScript 1.6.3
(function() {
  var MongoClient, dbconnection;

  MongoClient = require('mongodb').MongoClient;

  module.exports = dbconnection = (function() {
    function dbconnection() {}

    dbconnection.db = null;

    dbconnection.get_client = function(fn) {
      var _this = this;
      if (dbconnection.db !== null) {
        return fn(null, dbconnection.db);
      } else {
        return MongoClient.connect('mongodb://127.0.0.1:27017/trellme', function(err, db) {
          if (err) {
            throw err;
          } else {
            dbconnection.db = db;
            return fn(null, dbconnection.db);
          }
        });
      }
    };

    return dbconnection;

  })();

}).call(this);
