// Generated by CoffeeScript 1.6.3
(function() {
  var Trello, _;

  _ = require('underscore');

  module.exports = Trello = (function() {
    function Trello() {
      this;
    }

    Trello.prototype.filterBoards = function(json) {
      var boards, data, e,
        _this = this;
      try {
        data = JSON.parse(json);
      } catch (_error) {
        e = _error;
        return null;
      }
      boards = [];
      _.each(data, function(board) {
        var b;
        b = {
          id: board.id,
          name: board.name,
          closed: board.closed
        };
        return boards.push(b);
      });
      return boards;
    };

    Trello.prototype.filterLists = function(json) {
      var data, e, lists,
        _this = this;
      try {
        data = JSON.parse(json);
      } catch (_error) {
        e = _error;
        return null;
      }
      lists = [];
      _.each(data, function(list) {
        var lst;
        lst = {
          id: list.id,
          name: list.name,
          closed: list.closed
        };
        return lists.push(lst);
      });
      return lists;
    };

    Trello.prototype.filterCards = function(json) {
      var data, e;
      try {
        data = JSON.parse(json);
      } catch (_error) {
        e = _error;
        return null;
      }
      return data;
    };

    filterChecklist;

    return Trello;

  })();

}).call(this);
