// Generated by CoffeeScript 1.6.3
(function() {
  var ObjectID, Users, dbconnection, mongodb, should,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  mongodb = require('mongodb');

  ObjectID = require('mongodb').ObjectID;

  dbconnection = require('./dbconnection');

  should = require('should');

  module.exports = Users = (function(_super) {
    __extends(Users, _super);

    function Users() {
      Users.__super__.constructor.call(this);
    }

    Users.prototype.findByEmail = function(obj, fn) {
      var client,
        _this = this;
      client = dbconnection.get_client();
      return client.open(function(err, p_client) {
        return client.collection('users', function(err, col) {
          if (err) {
            console.log(err);
            client.close();
            return fn(err, null);
          }
          return col.findOne({
            "email": obj.username
          }, function(err, user) {
            client.close();
            return fn(err, user);
          });
        });
      });
    };

    Users.prototype.verifyPassword = function(user, password) {
      var r;
      r = user.password === password;
      console.log(r);
      return r;
    };

    Users.prototype.findAll = function(fn) {
      var client,
        _this = this;
      client = dbconnection.get_client();
      return client.open(function(err, p_client) {
        return client.collection('users', function(err, col) {
          if (err) {
            console.log(err);
            client.close();
            return fn(err, null);
          }
          return col.find({}, function(err, cursor) {
            if (err) {
              console.log(err);
              client.close();
              return fn(err, null);
            }
            return cursor.toArray(function(err, items) {
              items.length.should.be.above(0);
              client.close();
              return fn(err, items);
            });
          });
        });
      });
    };

    Users.prototype.save_token_secret = function(user_id, value, fn) {
      var client,
        _this = this;
      client = dbconnection.get_client();
      return client.open(function(err, p_client) {
        return client.collection('users', function(err, col) {
          if (err) {
            console.log(err);
            client.close();
            return fn(err, null);
          }
          return col.update({
            _id: user_id
          }, {
            $set: {
              token_secret: value
            }
          }, function(err) {
            client.close();
            if (err) {
              console.log(err);
              return fn(err, null);
            } else {
              return fn(null, "update success");
            }
          });
        });
      });
    };

    Users.prototype.save_access_token = function(user_id, values, fn) {
      var client,
        _this = this;
      client = dbconnection.get_client();
      return client.open(function(err, p_client) {
        return client.collection('users', function(err, col) {
          if (err) {
            console.log(err);
            client.close();
            return fn(err, null);
          }
          return col.update({
            _id: new ObjectID(user_id)
          }, {
            $set: values
          }, function(err) {
            client.close();
            if (err) {
              console.log(err);
              return fn(err, null);
            } else {
              return fn(null, "update success");
            }
          });
        });
      });
    };

    Users.prototype.get = function(user_id, fn) {
      var client,
        _this = this;
      client = dbconnection.get_client();
      return client.open(function(err, p_client) {
        return client.collection('users', function(err, col) {
          if (err) {
            client.close();
            console.log(err);
            fn(err, null);
            return;
          }
          return col.findOne({
            _id: new ObjectID(user_id)
          }, function(err, user) {
            client.close();
            console.log("users.get success " + user_id);
            console.log(user);
            return fn(null, user);
          });
        });
      });
    };

    Users.prototype.add = function(params, fn) {
      var client,
        _this = this;
      should.exist(params.email);
      should.exist(params.password);
      should.exist(params.trello_username);
      if (!params.email.match(/^[a-zA-Z0-9\\.!#$%&'*+\-/=?\^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/)) {
        fn(500, "Invalid email address");
        return;
      }
      if (!params.trello_username.match(/^[a-zA-Z\\.\-0-9_]+$/)) {
        fn(500, "Invalid Trello username");
        return;
      }
      client = dbconnection.get_client();
      return client.open(function(err, p_client) {
        return p_client.collection('users', function(err, col) {
          var values;
          if (err) {
            p_client.close();
            fn(500, "Failed to insert a user");
            return;
          }
          values = {
            email: params.email,
            password: params.password,
            trello_username: params.trello_username,
            created: new Date()
          };
          return col.insert(values, function(err, docs) {
            p_client.close();
            return fn(null, "Add user suceess");
          });
        });
      });
    };

    Users.prototype.remove = function(user_id, fn) {
      var client,
        _this = this;
      should.exist(user_id);
      client = dbconnection.get_client();
      return client.open(function(err, p_client) {
        return p_client.collection('users', function(err, col) {
          if (err) {
            p_client.close();
            fn(500, "Failed to insert a user");
            return;
          }
          return col.remove({
            _id: new ObjectID(user_id)
          }, function(err, docs) {
            p_client.close();
            return fn(null, "Remove user suceess");
          });
        });
      });
    };

    return Users;

  })(dbconnection);

}).call(this);
