// Generated by CoffeeScript 1.6.3
(function() {
  var Actions, ObjectID, db, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ObjectID = require('mongodb').ObjectID;

  db = require('./dbconnection');

  module.exports = Actions = (function(_super) {
    __extends(Actions, _super);

    function Actions() {
      _ref = Actions.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Actions.colName = 'actions';

    Actions.index('data.board.id');

    Actions.index('user_id');

    Actions.findByBoardId = function(boardId, cb) {
      if (boardId instanceof ObjectID) {
        boardId = boardId.toString();
      }
      return this.collection(function(err, col) {
        if (err) {
          return cb(err, null);
        }
        return col.find({
          'data.board.id': boardId
        }).toArray(cb);
      });
    };

    Actions.findByUserId = function(userId, cb) {
      if (!(userId instanceof ObjectID)) {
        userId = new ObjectID(userId);
      }
      return this.collection(function(err, col) {
        if (err) {
          return cb(err, null);
        }
        return col.find({
          user_id: userId
        }).toArray(cb);
      });
    };

    return Actions;

  })(db);

}).call(this);
