// Generated by CoffeeScript 1.6.3
(function() {
  var MongoClient, dbconnection;

  MongoClient = require('mongodb').MongoClient;

  module.exports = dbconnection = (function() {
    function dbconnection() {}

    dbconnection.db = null;

    dbconnection.get_client = function(fn) {
      var _this = this;
      if (dbconnection.db !== null) {
        return fn(null, dbconnection.db);
      } else {
        return MongoClient.connect('mongodb://127.0.0.1:27017/trellme', function(err, db) {
          if (err) {
            throw err;
          } else {
            dbconnection.db = db;
            return fn(null, dbconnection.db);
          }
        });
      }
    };

    dbconnection.collection = function(cb) {
      var _this = this;
      if (this.colName === void 0) {
        throw new Error('colName not defined');
      }
      return this.get_client(function(err, client) {
        if (err) {
          return cb(err, null);
        }
        return client.collection(_this.colName, cb);
      });
    };

    return dbconnection;

  })();

}).call(this);
