// Generated by CoffeeScript 1.6.3
(function() {
  var Members, ObjectID, db, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ObjectID = require('mongodb').ObjectID;

  db = require('./dbconnection');

  module.exports = Members = (function(_super) {
    __extends(Members, _super);

    function Members() {
      _ref = Members.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Members.colName = 'members';

    Members.findByMemberId = function(memberId, cb) {
      if (memberId instanceof ObjectID) {
        memberId = memberId.toString();
      }
      return this.collection(function(err, col) {
        if (err) {
          return cb(err, null);
        }
        return col.find({
          member_id: memberId
        }).toArray(cb);
      });
    };

    Members.findByUserId = function(userId, cb) {
      if (!(userId instanceof ObjectID)) {
        userId = new ObjectID(userId);
      }
      return this.collection(function(err, col) {
        if (err) {
          return cb(err, null);
        }
        return col.find({
          user_id: userId
        }).toArray(cb);
      });
    };

    return Members;

  })(db);

}).call(this);
